package sopnovubon.mytravel.domain;
// Generated Jul 23, 2018 9:00:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CencelBooking generated by hbm2java
 */
@Entity
@Table(name="cencel_booking"
    ,catalog="sopnovubon"
)
public class CencelBooking  implements java.io.Serializable {


     private Integer cencelBookingId;
     private ConfirmBooking confirmBooking;
     private CustomerRegistration customerRegistration;
     private Date cenceletionDate;

    public CencelBooking() {
    }

    public CencelBooking(ConfirmBooking confirmBooking, CustomerRegistration customerRegistration, Date cenceletionDate) {
       this.confirmBooking = confirmBooking;
       this.customerRegistration = customerRegistration;
       this.cenceletionDate = cenceletionDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cencel_booking_id", unique=true, nullable=false)
    public Integer getCencelBookingId() {
        return this.cencelBookingId;
    }
    
    public void setCencelBookingId(Integer cencelBookingId) {
        this.cencelBookingId = cencelBookingId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="booking_id", nullable=false)
    public ConfirmBooking getConfirmBooking() {
        return this.confirmBooking;
    }
    
    public void setConfirmBooking(ConfirmBooking confirmBooking) {
        this.confirmBooking = confirmBooking;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cust_id", nullable=false)
    public CustomerRegistration getCustomerRegistration() {
        return this.customerRegistration;
    }
    
    public void setCustomerRegistration(CustomerRegistration customerRegistration) {
        this.customerRegistration = customerRegistration;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="cenceletion_date", nullable=false, length=10)
    public Date getCenceletionDate() {
        return this.cenceletionDate;
    }
    
    public void setCenceletionDate(Date cenceletionDate) {
        this.cenceletionDate = cenceletionDate;
    }




}


