package sopnovubon.mytravel.domain;
// Generated Jul 23, 2018 9:00:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ConfirmHotelReservation generated by hbm2java
 */
@Entity
@Table(name="confirm_hotel_reservation"
    ,catalog="sopnovubon"
)
public class ConfirmHotelReservation  implements java.io.Serializable {


     private Integer hotelReservationId;
     private CustomerRegistration customerRegistration;
     private HotelReservation hotelReservation;
     private Date reservationDate;
     private Date checkIn;
     private Date checkOut;

    public ConfirmHotelReservation() {
    }

    public ConfirmHotelReservation(CustomerRegistration customerRegistration, HotelReservation hotelReservation, Date reservationDate, Date checkIn, Date checkOut) {
       this.customerRegistration = customerRegistration;
       this.hotelReservation = hotelReservation;
       this.reservationDate = reservationDate;
       this.checkIn = checkIn;
       this.checkOut = checkOut;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="hotel_reservation_id", unique=true, nullable=false)
    public Integer getHotelReservationId() {
        return this.hotelReservationId;
    }
    
    public void setHotelReservationId(Integer hotelReservationId) {
        this.hotelReservationId = hotelReservationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cust_id", nullable=false)
    public CustomerRegistration getCustomerRegistration() {
        return this.customerRegistration;
    }
    
    public void setCustomerRegistration(CustomerRegistration customerRegistration) {
        this.customerRegistration = customerRegistration;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="hotel_id", nullable=false)
    public HotelReservation getHotelReservation() {
        return this.hotelReservation;
    }
    
    public void setHotelReservation(HotelReservation hotelReservation) {
        this.hotelReservation = hotelReservation;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="reservation_Date", nullable=false, length=10)
    public Date getReservationDate() {
        return this.reservationDate;
    }
    
    public void setReservationDate(Date reservationDate) {
        this.reservationDate = reservationDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="check_In", nullable=false, length=10)
    public Date getCheckIn() {
        return this.checkIn;
    }
    
    public void setCheckIn(Date checkIn) {
        this.checkIn = checkIn;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="check_Out", nullable=false, length=10)
    public Date getCheckOut() {
        return this.checkOut;
    }
    
    public void setCheckOut(Date checkOut) {
        this.checkOut = checkOut;
    }




}


