package sopnovubon.mytravel.domain;
// Generated Jul 23, 2018 9:00:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CustomerRegistration generated by hbm2java
 */
@Entity
@Table(name="customer_registration"
    ,catalog="sopnovubon"
)
public class CustomerRegistration  implements java.io.Serializable {


     private Integer custId;
     private String firstName;
     private String lastName;
     private String address;
     private String mobile;
     private String email;
     private String userName;
     private String password;
     private Set<PaymentSystem> paymentSystems = new HashSet<PaymentSystem>(0);
     private Set<ConfirmBooking> confirmBookings = new HashSet<ConfirmBooking>(0);
     private Set<ConfirmHotelReservation> confirmHotelReservations = new HashSet<ConfirmHotelReservation>(0);
     private Set<CencelBooking> cencelBookings = new HashSet<CencelBooking>(0);
     private Set<CustomerFeedback> customerFeedbacks = new HashSet<CustomerFeedback>(0);

    public CustomerRegistration() {
    }

	
    public CustomerRegistration(String firstName, String lastName, String address, String mobile, String email, String userName, String password) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.address = address;
        this.mobile = mobile;
        this.email = email;
        this.userName = userName;
        this.password = password;
    }
    public CustomerRegistration(String firstName, String lastName, String address, String mobile, String email, String userName, String password, Set<PaymentSystem> paymentSystems, Set<ConfirmBooking> confirmBookings, Set<ConfirmHotelReservation> confirmHotelReservations, Set<CencelBooking> cencelBookings, Set<CustomerFeedback> customerFeedbacks) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.address = address;
       this.mobile = mobile;
       this.email = email;
       this.userName = userName;
       this.password = password;
       this.paymentSystems = paymentSystems;
       this.confirmBookings = confirmBookings;
       this.confirmHotelReservations = confirmHotelReservations;
       this.cencelBookings = cencelBookings;
       this.customerFeedbacks = customerFeedbacks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="cust_id", unique=true, nullable=false)
    public Integer getCustId() {
        return this.custId;
    }
    
    public void setCustId(Integer custId) {
        this.custId = custId;
    }

    
    @Column(name="first_name", nullable=false, length=45)
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    
    @Column(name="last_name", nullable=false, length=45)
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    
    @Column(name="address", nullable=false, length=50)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="mobile", nullable=false, length=20)
    public String getMobile() {
        return this.mobile;
    }
    
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="user_name", nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    
    @Column(name="password", nullable=false, length=45)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerRegistration")
    public Set<PaymentSystem> getPaymentSystems() {
        return this.paymentSystems;
    }
    
    public void setPaymentSystems(Set<PaymentSystem> paymentSystems) {
        this.paymentSystems = paymentSystems;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerRegistration")
    public Set<ConfirmBooking> getConfirmBookings() {
        return this.confirmBookings;
    }
    
    public void setConfirmBookings(Set<ConfirmBooking> confirmBookings) {
        this.confirmBookings = confirmBookings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerRegistration")
    public Set<ConfirmHotelReservation> getConfirmHotelReservations() {
        return this.confirmHotelReservations;
    }
    
    public void setConfirmHotelReservations(Set<ConfirmHotelReservation> confirmHotelReservations) {
        this.confirmHotelReservations = confirmHotelReservations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerRegistration")
    public Set<CencelBooking> getCencelBookings() {
        return this.cencelBookings;
    }
    
    public void setCencelBookings(Set<CencelBooking> cencelBookings) {
        this.cencelBookings = cencelBookings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="customerRegistration")
    public Set<CustomerFeedback> getCustomerFeedbacks() {
        return this.customerFeedbacks;
    }
    
    public void setCustomerFeedbacks(Set<CustomerFeedback> customerFeedbacks) {
        this.customerFeedbacks = customerFeedbacks;
    }




}


