package sopnovubon.mytravel.domain;
// Generated Jul 23, 2018 9:00:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PackageSubCategory generated by hbm2java
 */
@Entity
@Table(name="package_sub_category"
    ,catalog="sopnovubon"
)
public class PackageSubCategory  implements java.io.Serializable {


     private Integer packSubCatId;
     private PackageCategory packageCategory;
     private String packSubCatName;
     private Set<Pack> packs = new HashSet<Pack>(0);

    public PackageSubCategory() {
    }

	
    public PackageSubCategory(PackageCategory packageCategory, String packSubCatName) {
        this.packageCategory = packageCategory;
        this.packSubCatName = packSubCatName;
    }
    public PackageSubCategory(PackageCategory packageCategory, String packSubCatName, Set<Pack> packs) {
       this.packageCategory = packageCategory;
       this.packSubCatName = packSubCatName;
       this.packs = packs;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pack_sub_cat_id", unique=true, nullable=false)
    public Integer getPackSubCatId() {
        return this.packSubCatId;
    }
    
    public void setPackSubCatId(Integer packSubCatId) {
        this.packSubCatId = packSubCatId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pack_cat_id", nullable=false)
    public PackageCategory getPackageCategory() {
        return this.packageCategory;
    }
    
    public void setPackageCategory(PackageCategory packageCategory) {
        this.packageCategory = packageCategory;
    }

    
    @Column(name="pack_sub_cat_name", nullable=false, length=45)
    public String getPackSubCatName() {
        return this.packSubCatName;
    }
    
    public void setPackSubCatName(String packSubCatName) {
        this.packSubCatName = packSubCatName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="packageSubCategory")
    public Set<Pack> getPacks() {
        return this.packs;
    }
    
    public void setPacks(Set<Pack> packs) {
        this.packs = packs;
    }




}


