package sopnovubon.mytravel.domain;
// Generated Jul 23, 2018 9:00:19 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * PackageCategory generated by hbm2java
 */
@Entity
@Table(name="package_category"
    ,catalog="sopnovubon"
)
public class PackageCategory  implements java.io.Serializable {


     private Integer packCatId;
     private String packCatName;
     private Set<Pack> packs = new HashSet<Pack>(0);
     private Set<PackageSubCategory> packageSubCategories = new HashSet<PackageSubCategory>(0);

    public PackageCategory() {
    }

	
    public PackageCategory(String packCatName) {
        this.packCatName = packCatName;
    }
    public PackageCategory(String packCatName, Set<Pack> packs, Set<PackageSubCategory> packageSubCategories) {
       this.packCatName = packCatName;
       this.packs = packs;
       this.packageSubCategories = packageSubCategories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pack_cat_id", unique=true, nullable=false)
    public Integer getPackCatId() {
        return this.packCatId;
    }
    
    public void setPackCatId(Integer packCatId) {
        this.packCatId = packCatId;
    }

    
    @Column(name="pack_cat_name", nullable=false, length=45)
    public String getPackCatName() {
        return this.packCatName;
    }
    
    public void setPackCatName(String packCatName) {
        this.packCatName = packCatName;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="packageCategory")
    public Set<Pack> getPacks() {
        return this.packs;
    }
    
    public void setPacks(Set<Pack> packs) {
        this.packs = packs;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="packageCategory")
    public Set<PackageSubCategory> getPackageSubCategories() {
        return this.packageSubCategories;
    }
    
    public void setPackageSubCategories(Set<PackageSubCategory> packageSubCategories) {
        this.packageSubCategories = packageSubCategories;
    }




}


