package sopnovubon.mytravel.domain;
// Generated Jul 23, 2018 9:00:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pack generated by hbm2java
 */
@Entity
@Table(name="pack"
    ,catalog="sopnovubon"
)
public class Pack  implements java.io.Serializable {


     private Integer packId;
     private PackageCategory packageCategory;
     private PackageSubCategory packageSubCategory;
     private String place;
     private int numberOfDay;
     private int numberOfNight;
     private Integer numberOfAdult;
     private Integer numberOfChild;
     private double accommodationCost;
     private Double busCost;
     private Double trainCost;
     private Double airCost;
     private Double guideServiceCost;
     private Date departureDate;
     private Date returnDate;
     private Double extraService;
     private double total;
     private int availablePackage;
     private String hotelName;
     private String imageUrl;
     private Set<ConfirmBooking> confirmBookings = new HashSet<ConfirmBooking>(0);
     private Set<CustomerFeedback> customerFeedbacks = new HashSet<CustomerFeedback>(0);

    public Pack() {
    }

	
    public Pack(PackageCategory packageCategory, PackageSubCategory packageSubCategory, String place, int numberOfDay, int numberOfNight, double accommodationCost, Date departureDate, Date returnDate, double total, int availablePackage, String hotelName, String imageUrl) {
        this.packageCategory = packageCategory;
        this.packageSubCategory = packageSubCategory;
        this.place = place;
        this.numberOfDay = numberOfDay;
        this.numberOfNight = numberOfNight;
        this.accommodationCost = accommodationCost;
        this.departureDate = departureDate;
        this.returnDate = returnDate;
        this.total = total;
        this.availablePackage = availablePackage;
        this.hotelName = hotelName;
        this.imageUrl = imageUrl;
    }
    public Pack(PackageCategory packageCategory, PackageSubCategory packageSubCategory, String place, int numberOfDay, int numberOfNight, Integer numberOfAdult, Integer numberOfChild, double accommodationCost, Double busCost, Double trainCost, Double airCost, Double guideServiceCost, Date departureDate, Date returnDate, Double extraService, double total, int availablePackage, String hotelName, String imageUrl, Set<ConfirmBooking> confirmBookings, Set<CustomerFeedback> customerFeedbacks) {
       this.packageCategory = packageCategory;
       this.packageSubCategory = packageSubCategory;
       this.place = place;
       this.numberOfDay = numberOfDay;
       this.numberOfNight = numberOfNight;
       this.numberOfAdult = numberOfAdult;
       this.numberOfChild = numberOfChild;
       this.accommodationCost = accommodationCost;
       this.busCost = busCost;
       this.trainCost = trainCost;
       this.airCost = airCost;
       this.guideServiceCost = guideServiceCost;
       this.departureDate = departureDate;
       this.returnDate = returnDate;
       this.extraService = extraService;
       this.total = total;
       this.availablePackage = availablePackage;
       this.hotelName = hotelName;
       this.imageUrl = imageUrl;
       this.confirmBookings = confirmBookings;
       this.customerFeedbacks = customerFeedbacks;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="pack_id", unique=true, nullable=false)
    public Integer getPackId() {
        return this.packId;
    }
    
    public void setPackId(Integer packId) {
        this.packId = packId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pack_cat_id", nullable=false)
    public PackageCategory getPackageCategory() {
        return this.packageCategory;
    }
    
    public void setPackageCategory(PackageCategory packageCategory) {
        this.packageCategory = packageCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="pack_sub_cat_id", nullable=false)
    public PackageSubCategory getPackageSubCategory() {
        return this.packageSubCategory;
    }
    
    public void setPackageSubCategory(PackageSubCategory packageSubCategory) {
        this.packageSubCategory = packageSubCategory;
    }

    
    @Column(name="place", nullable=false, length=200)
    public String getPlace() {
        return this.place;
    }
    
    public void setPlace(String place) {
        this.place = place;
    }

    
    @Column(name="numberOfDay", nullable=false)
    public int getNumberOfDay() {
        return this.numberOfDay;
    }
    
    public void setNumberOfDay(int numberOfDay) {
        this.numberOfDay = numberOfDay;
    }

    
    @Column(name="numberOfNight", nullable=false)
    public int getNumberOfNight() {
        return this.numberOfNight;
    }
    
    public void setNumberOfNight(int numberOfNight) {
        this.numberOfNight = numberOfNight;
    }

    
    @Column(name="numberOfAdult")
    public Integer getNumberOfAdult() {
        return this.numberOfAdult;
    }
    
    public void setNumberOfAdult(Integer numberOfAdult) {
        this.numberOfAdult = numberOfAdult;
    }

    
    @Column(name="numberOfChild")
    public Integer getNumberOfChild() {
        return this.numberOfChild;
    }
    
    public void setNumberOfChild(Integer numberOfChild) {
        this.numberOfChild = numberOfChild;
    }

    
    @Column(name="accommodationCost", nullable=false, precision=22, scale=0)
    public double getAccommodationCost() {
        return this.accommodationCost;
    }
    
    public void setAccommodationCost(double accommodationCost) {
        this.accommodationCost = accommodationCost;
    }

    
    @Column(name="busCost", precision=22, scale=0)
    public Double getBusCost() {
        return this.busCost;
    }
    
    public void setBusCost(Double busCost) {
        this.busCost = busCost;
    }

    
    @Column(name="trainCost", precision=22, scale=0)
    public Double getTrainCost() {
        return this.trainCost;
    }
    
    public void setTrainCost(Double trainCost) {
        this.trainCost = trainCost;
    }

    
    @Column(name="airCost", precision=22, scale=0)
    public Double getAirCost() {
        return this.airCost;
    }
    
    public void setAirCost(Double airCost) {
        this.airCost = airCost;
    }

    
    @Column(name="guideServiceCost", precision=22, scale=0)
    public Double getGuideServiceCost() {
        return this.guideServiceCost;
    }
    
    public void setGuideServiceCost(Double guideServiceCost) {
        this.guideServiceCost = guideServiceCost;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="departureDate", nullable=false, length=10)
    public Date getDepartureDate() {
        return this.departureDate;
    }
    
    public void setDepartureDate(Date departureDate) {
        this.departureDate = departureDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="returnDate", nullable=false, length=10)
    public Date getReturnDate() {
        return this.returnDate;
    }
    
    public void setReturnDate(Date returnDate) {
        this.returnDate = returnDate;
    }

    
    @Column(name="extraService", precision=22, scale=0)
    public Double getExtraService() {
        return this.extraService;
    }
    
    public void setExtraService(Double extraService) {
        this.extraService = extraService;
    }

    
    @Column(name="total", nullable=false, precision=22, scale=0)
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }

    
    @Column(name="availablePackage", nullable=false)
    public int getAvailablePackage() {
        return this.availablePackage;
    }
    
    public void setAvailablePackage(int availablePackage) {
        this.availablePackage = availablePackage;
    }

    
    @Column(name="hotelName", nullable=false, length=100)
    public String getHotelName() {
        return this.hotelName;
    }
    
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName;
    }

    
    @Column(name="imageURL", nullable=false, length=200)
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pack")
    public Set<ConfirmBooking> getConfirmBookings() {
        return this.confirmBookings;
    }
    
    public void setConfirmBookings(Set<ConfirmBooking> confirmBookings) {
        this.confirmBookings = confirmBookings;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="pack")
    public Set<CustomerFeedback> getCustomerFeedbacks() {
        return this.customerFeedbacks;
    }
    
    public void setCustomerFeedbacks(Set<CustomerFeedback> customerFeedbacks) {
        this.customerFeedbacks = customerFeedbacks;
    }




}


