package sopnovubon.mytravel.domain;
// Generated Jul 23, 2018 9:00:19 PM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PaymentSystem generated by hbm2java
 */
@Entity
@Table(name="payment_system"
    ,catalog="sopnovubon"
)
public class PaymentSystem  implements java.io.Serializable {


     private Integer paymentId;
     private ConfirmBooking confirmBooking;
     private CustomerRegistration customerRegistration;
     private String cardNo;
     private String cvvNo;
     private Date expireDate;

    public PaymentSystem() {
    }

    public PaymentSystem(ConfirmBooking confirmBooking, CustomerRegistration customerRegistration, String cardNo, String cvvNo, Date expireDate) {
       this.confirmBooking = confirmBooking;
       this.customerRegistration = customerRegistration;
       this.cardNo = cardNo;
       this.cvvNo = cvvNo;
       this.expireDate = expireDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="payment_id", unique=true, nullable=false)
    public Integer getPaymentId() {
        return this.paymentId;
    }
    
    public void setPaymentId(Integer paymentId) {
        this.paymentId = paymentId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="booking_id", nullable=false)
    public ConfirmBooking getConfirmBooking() {
        return this.confirmBooking;
    }
    
    public void setConfirmBooking(ConfirmBooking confirmBooking) {
        this.confirmBooking = confirmBooking;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="cust_id", nullable=false)
    public CustomerRegistration getCustomerRegistration() {
        return this.customerRegistration;
    }
    
    public void setCustomerRegistration(CustomerRegistration customerRegistration) {
        this.customerRegistration = customerRegistration;
    }

    
    @Column(name="card_no", nullable=false, length=30)
    public String getCardNo() {
        return this.cardNo;
    }
    
    public void setCardNo(String cardNo) {
        this.cardNo = cardNo;
    }

    
    @Column(name="cvv_no", nullable=false, length=30)
    public String getCvvNo() {
        return this.cvvNo;
    }
    
    public void setCvvNo(String cvvNo) {
        this.cvvNo = cvvNo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="expire_Date", nullable=false, length=10)
    public Date getExpireDate() {
        return this.expireDate;
    }
    
    public void setExpireDate(Date expireDate) {
        this.expireDate = expireDate;
    }




}


